#!/usr/bin/env bash

# bash completion for Maven Version Manager (NVM)

__mvm_generate_completion()
{
  declare current_word
  current_word="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "$1" -- "$current_word"))
  return 0
}

__mvm_commands ()
{
  declare current_word
  declare command

  current_word="${COMP_WORDS[COMP_CWORD]}"

  COMMANDS='\
    help install uninstall use run\
    ls ls-remote list list-remote deactivate\
    alias unalias copy-packages clear-cache version'

    if [ ${#COMP_WORDS[@]} == 4 ]; then

      command="${COMP_WORDS[COMP_CWORD-2]}"
      case "${command}" in
      alias)  __mvm_installed_nodes ;;
      esac

    else

      case "${current_word}" in
      -*)     __mvm_options ;;
      *)      __mvm_generate_completion "$COMMANDS" ;;
      esac

    fi
}

__mvm_options ()
{
  OPTIONS=''
  __mvm_generate_completion "$OPTIONS"
}

__mvm_installed_nodes ()
{
  __mvm_generate_completion "$(mvm_ls) $(__mvm_aliases)"
}

__mvm_aliases ()
{
  declare aliases
  aliases=""
  if [ -d $NVM_DIR/alias ]; then
    aliases="`cd $NVM_DIR/alias && ls`"
  fi
  echo "${aliases}"
}

__mvm_alias ()
{
  __mvm_generate_completion "$(__mvm_aliases)"
}

__mvm ()
{
  declare previous_word
  previous_word="${COMP_WORDS[COMP_CWORD-1]}"

  case "$previous_word" in
  use|run|ls|list|uninstall) __mvm_installed_nodes ;;
  alias|unalias)  __mvm_alias ;;
  *)              __mvm_commands ;;
  esac

  return 0
}

# complete is a bash builtin, but recent versions of ZSH come with a function 
# called bashcompinit that will create a complete in ZSH. If the user is in 
# ZSH, load and run bashcompinit before calling the complete function.
if [[ -n ${ZSH_VERSION-} ]]; then
	autoload -U +X bashcompinit && bashcompinit
fi

complete -o default -o nospace -F __mvm mvm
